name: cfHideDeathMsg
main: ru.cronfire.cfhidedeathmsg.CronFireHideDeathMessage
version: 1.3
description: Plugin will hide death messages.
authors: [Zeluboba, toxuin]
maintainer: Zeluboba
website: http://cronfire.ru/